import { TilingGenerationOptions } from './tiling-geometries';
import { Mesh, OperatorSpec } from './conway-operators';
import { MeshFinalizationMode } from './mesh-finalization';
import { PaletteKey } from './palettes';
import { ColorMode, computeFaceColors } from './coloring';
import { RadialPolyType } from './radial-solids';
import { generateFinalMesh } from './mesh-pipeline';

const ZIP_LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
const ZIP_CENTRAL_DIRECTORY_SIGNATURE = 0x02014b50;
const ZIP_END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50;
const ZIP_VERSION = 20;
const CRC32_TABLE = createCrc32Table();

export async function sendToBlender(
  mode: '2d' | '3d',
  tilingType: string,
  rows: number,
  cols: number,
  operators: OperatorSpec[],
  paletteKey: PaletteKey,
  colorMode: ColorMode,
  radialType: RadialPolyType,
  radialSides: number,
  generationOptions?: TilingGenerationOptions,
  finalization: MeshFinalizationMode = 'planarize',
): Promise<{ ok: boolean; error?: string }> {
  const mesh = generateFinalMesh({ mode, tilingType, rows, cols, operators, radialType, radialSides, generationOptions, finalization });
  if (!mesh) return { ok: false, error: 'No mesh generated' };

  const faceColors = computeFaceColors(mesh, paletteKey, colorMode);
  const payload = {
    vertices: Array.from(mesh.vertices),
    faces: mesh.faces,
    colors: faceColors,
  };

  try {
    const res = await fetch('http://localhost:8765/polyhydra', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) return { ok: false, error: `Blender server responded with ${res.status}` };
    return { ok: true };
  } catch {
    return { ok: false, error: 'Could not connect — is the Blender addon running?' };
  }
}

export function exportObj(
  mode: '2d' | '3d',
  tilingType: string,
  rows: number,
  cols: number,
  operators: OperatorSpec[],
  paletteKey: PaletteKey,
  colorMode: ColorMode,
  radialType: RadialPolyType,
  radialSides: number,
  generationOptions?: TilingGenerationOptions,
  finalization: MeshFinalizationMode = 'planarize',
) {
  const mesh = generateFinalMesh({
    mode,
    tilingType,
    rows,
    cols,
    operators,
    radialType,
    radialSides,
    generationOptions,
    finalization,
  });
  if (!mesh) return;

  const faceColors = computeFaceColors(mesh, paletteKey, colorMode);
  const { obj, mtl } = generateObjAndMtl(mesh, faceColors);
  const zipBlob = createZipBlob([
    { name: 'polyhydra-export.obj', content: obj },
    { name: 'polyhydra-export.mtl', content: mtl },
  ]);
  downloadBlob(zipBlob, 'polyhydra-export.zip');
}

export function exportOff(
  mode: '2d' | '3d',
  tilingType: string,
  rows: number,
  cols: number,
  operators: OperatorSpec[],
  paletteKey: PaletteKey,
  colorMode: ColorMode,
  radialType: RadialPolyType,
  radialSides: number,
  generationOptions?: TilingGenerationOptions,
  finalization: MeshFinalizationMode = 'planarize',
) {
  const mesh = generateFinalMesh({
    mode,
    tilingType,
    rows,
    cols,
    operators,
    radialType,
    radialSides,
    generationOptions,
    finalization,
  });
  if (!mesh) return;

  const faceColors = computeFaceColors(mesh, paletteKey, colorMode);

  const numVertices = mesh.vertices.length / 3;
  const numFaces = mesh.faces.length;
  
  let off = `COFF\n${numVertices} ${numFaces} 0\n`;
  
  for (let i = 0; i < mesh.vertices.length; i += 3) {
    off += `${mesh.vertices[i]} ${mesh.vertices[i + 1]} ${mesh.vertices[i + 2]}\n`;
  }
  
  for (let fIdx = 0; fIdx < mesh.faces.length; fIdx++) {
    const face = mesh.faces[fIdx];
    const colorHex = faceColors[fIdx] || "#ffffff";
    const { r, g, b } = hexToRgb(colorHex);
    off += `${face.length} ${face.join(' ')} ${r} ${g} ${b} 255\n`;
  }

  downloadString(off, 'polyhydra-export.off', 'text/plain');
}

function hexToRgb(hex: string) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : { r: 255, g: 255, b: 255 };
}

function generateObjAndMtl(mesh: Mesh, faceColors: string[]) {
  const colorToMaterial = new Map<string, string>();
  const materialOrder: string[] = [];

  let obj = '# Generated by polyhydra-web\n';
  obj += 'mtllib polyhydra-export.mtl\n';
  obj += 'o polyhydra-export\n';

  for (let i = 0; i < mesh.vertices.length; i += 3) {
    obj += `v ${mesh.vertices[i]} ${mesh.vertices[i + 1]} ${mesh.vertices[i + 2]}\n`;
  }

  let activeMaterial: string | null = null;
  for (let fIdx = 0; fIdx < mesh.faces.length; fIdx++) {
    const face = mesh.faces[fIdx];
    const normalizedColor = normalizeHexColor(faceColors[fIdx] || '#ffffff');
    let materialName = colorToMaterial.get(normalizedColor);
    if (!materialName) {
      materialName = `mat_${normalizedColor.slice(1)}`;
      colorToMaterial.set(normalizedColor, materialName);
      materialOrder.push(normalizedColor);
    }
    if (materialName !== activeMaterial) {
      obj += `usemtl ${materialName}\n`;
      activeMaterial = materialName;
    }
    obj += `f ${face.map((idx) => idx + 1).join(' ')}\n`;
  }

  let mtl = '# Generated by polyhydra-web\n';
  for (const color of materialOrder) {
    const materialName = colorToMaterial.get(color)!;
    const { r, g, b } = hexToRgb(color);
    mtl += `newmtl ${materialName}\n`;
    mtl += 'Ka 0.000000 0.000000 0.000000\n';
    mtl += `Kd ${(r / 255).toFixed(6)} ${(g / 255).toFixed(6)} ${(b / 255).toFixed(6)}\n`;
    mtl += 'Ks 0.000000 0.000000 0.000000\n';
    mtl += 'd 1.000000\n';
    mtl += 'illum 1\n\n';
  }

  return { obj, mtl };
}

function normalizeHexColor(hex: string) {
  const result = /^#?([a-f\d]{6})$/i.exec(hex.trim());
  return result ? `#${result[1].toLowerCase()}` : '#ffffff';
}

function createZipBlob(files: Array<{ name: string; content: string }>) {
  const encoder = new TextEncoder();
  const localParts: Uint8Array[] = [];
  const centralParts: Uint8Array[] = [];
  const { dosDate, dosTime } = getDosDateTime(new Date());
  let offset = 0;

  for (const file of files) {
    const fileNameBytes = encoder.encode(file.name);
    const fileDataBytes = encoder.encode(file.content);
    const crc = crc32(fileDataBytes);

    const localHeader = new Uint8Array(30 + fileNameBytes.length);
    const localView = new DataView(localHeader.buffer);
    localView.setUint32(0, ZIP_LOCAL_FILE_HEADER_SIGNATURE, true);
    localView.setUint16(4, ZIP_VERSION, true);
    localView.setUint16(6, 0, true);
    localView.setUint16(8, 0, true);
    localView.setUint16(10, dosTime, true);
    localView.setUint16(12, dosDate, true);
    localView.setUint32(14, crc, true);
    localView.setUint32(18, fileDataBytes.length, true);
    localView.setUint32(22, fileDataBytes.length, true);
    localView.setUint16(26, fileNameBytes.length, true);
    localView.setUint16(28, 0, true);
    localHeader.set(fileNameBytes, 30);

    const centralHeader = new Uint8Array(46 + fileNameBytes.length);
    const centralView = new DataView(centralHeader.buffer);
    centralView.setUint32(0, ZIP_CENTRAL_DIRECTORY_SIGNATURE, true);
    centralView.setUint16(4, ZIP_VERSION, true);
    centralView.setUint16(6, ZIP_VERSION, true);
    centralView.setUint16(8, 0, true);
    centralView.setUint16(10, 0, true);
    centralView.setUint16(12, dosTime, true);
    centralView.setUint16(14, dosDate, true);
    centralView.setUint32(16, crc, true);
    centralView.setUint32(20, fileDataBytes.length, true);
    centralView.setUint32(24, fileDataBytes.length, true);
    centralView.setUint16(28, fileNameBytes.length, true);
    centralView.setUint16(30, 0, true);
    centralView.setUint16(32, 0, true);
    centralView.setUint16(34, 0, true);
    centralView.setUint16(36, 0, true);
    centralView.setUint32(38, 0, true);
    centralView.setUint32(42, offset, true);
    centralHeader.set(fileNameBytes, 46);

    localParts.push(localHeader, fileDataBytes);
    centralParts.push(centralHeader);
    offset += localHeader.length + fileDataBytes.length;
  }

  const centralDirectoryOffset = offset;
  const centralDirectorySize = centralParts.reduce((sum, part) => sum + part.length, 0);
  const endRecord = new Uint8Array(22);
  const endView = new DataView(endRecord.buffer);
  endView.setUint32(0, ZIP_END_OF_CENTRAL_DIRECTORY_SIGNATURE, true);
  endView.setUint16(4, 0, true);
  endView.setUint16(6, 0, true);
  endView.setUint16(8, files.length, true);
  endView.setUint16(10, files.length, true);
  endView.setUint32(12, centralDirectorySize, true);
  endView.setUint32(16, centralDirectoryOffset, true);
  endView.setUint16(20, 0, true);

  return new Blob([...localParts, ...centralParts, endRecord], { type: 'application/zip' });
}

function getDosDateTime(date: Date) {
  const year = Math.max(1980, date.getFullYear());
  const dosTime = (date.getSeconds() >> 1) | (date.getMinutes() << 5) | (date.getHours() << 11);
  const dosDate = date.getDate() | ((date.getMonth() + 1) << 5) | ((year - 1980) << 9);
  return { dosDate, dosTime };
}

function createCrc32Table() {
  const table = new Uint32Array(256);
  for (let i = 0; i < 256; i++) {
    let c = i;
    for (let bit = 0; bit < 8; bit++) {
      c = (c & 1) !== 0 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    }
    table[i] = c >>> 0;
  }
  return table;
}

function crc32(bytes: Uint8Array) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc = CRC32_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

export function exportSvg(
  mode: '2d' | '3d',
  tilingType: string,
  rows: number,
  cols: number,
  operators: OperatorSpec[],
  paletteKey: PaletteKey,
  colorMode: ColorMode,
  edgeColor: string,
  radialType: RadialPolyType,
  radialSides: number,
  generationOptions?: TilingGenerationOptions,
  finalization: MeshFinalizationMode = 'planarize',
) {
  const mesh = generateFinalMesh({
    mode,
    tilingType,
    rows,
    cols,
    operators,
    radialType,
    radialSides,
    generationOptions,
    finalization,
  });
  if (!mesh) return;

  const faceColors = computeFaceColors(mesh, paletteKey, colorMode);

  // Find bounds
  let minX = Infinity, maxX = -Infinity;
  let minY = Infinity, maxY = -Infinity;
  
  for (let i = 0; i < mesh.vertices.length; i += 3) {
    const x = mesh.vertices[i];
    const y = mesh.vertices[i + 1];
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  
  const padding = 1;
  const width = Math.max(0.1, maxX - minX) + padding * 2;
  const height = Math.max(0.1, maxY - minY) + padding * 2;
  const viewBox = `${minX - padding} ${-(maxY + padding)} ${width} ${height}`;

  // Y-axis in SVG goes down, but math goes up, so we negate Y.
  let svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n`;
  svg += `<svg width="${width * 50}" height="${height * 50}" viewBox="${viewBox}" xmlns="http://www.w3.org/2000/svg">\n`;
  svg += `<g stroke="${edgeColor}" stroke-width="0.05" stroke-linejoin="round">\n`;

  for (let fIdx = 0; fIdx < mesh.faces.length; fIdx++) {
    const face = mesh.faces[fIdx];
    let d = "";
    for (let i = 0; i < face.length; i++) {
      const idx = face[i] * 3;
      const x = mesh.vertices[idx];
      const y = -mesh.vertices[idx + 1]; // invert y
      if (i === 0) d += `M ${x} ${y} `;
      else d += `L ${x} ${y} `;
    }
    d += "Z";
    
    // Add fill to each path
    const fill = faceColors[fIdx] || "#ffffff";
    svg += `  <path d="${d}" fill="${fill}" />\n`;
  }

  svg += `</g>\n</svg>`;

  downloadString(svg, 'polyhydra-export.svg', 'image/svg+xml');
}

function downloadString(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  downloadBlob(blob, filename);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
